### ISSUE TITLE
Scheduler close failure occurs while spider closes

### ISSUE THREAD

**Issue by rdcprojects** [roycehaynes/scrapy-rabbitmq#4]
Below is the traceback:

```
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Python27\lib\site-packages\scrapy\core\engine.py", line 288, in <lambda>
    dfd.addBoth(lambda _: slot.scheduler.close(reason))
TypeError: close() takes exactly 1 argument (2 given)
```

**Comment by rdcprojects** [comment]
Never mind. Fixed in the latest commit.
